In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/save_model/homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)


LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[5000]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

Save Model
using pickle

In [8]:
import pickle

In [10]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [12]:
with open('/content/drive/MyDrive/Colab Notebooks/save_model/model_pickle','rb') as file:
    mp = pickle.load(file)

In [13]:
mp.predict([[5000]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

Save Trained Model Using joblib

In [16]:
import joblib

In [17]:
joblib.dump(model, '/content/drive/MyDrive/Colab Notebooks/save_model/model_joblib')

['/content/drive/MyDrive/Colab Notebooks/save_model/model_joblib']

In [18]:
mj = joblib.load('/content/drive/MyDrive/Colab Notebooks/save_model/model_joblib')

In [19]:
mj.coef_

array([135.78767123])

In [20]:
mj.intercept_

180616.43835616432

In [21]:
mj.predict([[5000]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])